# Generated by Django 5.2.5 on 2026-03-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbranch',
            options={'verbose_name': 'Ανάθεση Χρήστη σε Υποκατάστημα', 'verbose_name_plural': 'Αναθέσεις Χρηστών σε Υποκαταστήματα'},
        ),
    ]
