# Generated by Django 5.2.5 on 2026-03-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userbranch_options'),
        ('products', '0003_branch_address_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='userbranch',
            options={'verbose_name': 'User Branch', 'verbose_name_plural': 'User Branches'},
        ),
        migrations.AlterField(
            model_name='userbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.branch'),
        ),
    ]
