# Generated by Django 5.2.5 on 2026-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(blank=True, default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
