# Generated by Django 5.2.5 on 2026-03-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Εσωτερική Παραγγελία', 'verbose_name_plural': 'Εσωτερικές Παραγγελίες'},
        ),
        migrations.AlterModelOptions(
            name='internalorderitem',
            options={'verbose_name': 'Στοιχείο Παραγγελίας', 'verbose_name_plural': 'Στοιχεία Παραγγελίας'},
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='status',
            field=models.CharField(choices=[('unread', 'Αδιάβαστο'), ('read', 'Διαβάστηκε'), ('in_progress', 'Σε εξέλιξη'), ('ready', 'Έτοιμο'), ('delivered', 'Παραδόθηκε')], default='unread', max_length=20),
        ),
    ]
