# Generated by Django 5.2.5 on 2026-03-27 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_internalorder_options_and_more'),
        ('products', '0003_branch_address_branch_latitude_branch_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalorder',
            name='branch',
        ),
        migrations.AddField(
            model_name='internalorder',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='destination_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders_to_branch', to='products.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalorder',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='order_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Χαμηλή'), ('normal', 'Κανονική'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='internalorder',
            name='source_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders_from_branch', to='products.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Υποβλήθηκε'), ('in_progress', 'Σε προετοιμασία'), ('ready_for_pickup', 'Έτοιμη για παραλαβή'), ('picked_up', 'Παραλήφθηκε από οδηγό'), ('delivered', 'Παραδόθηκε'), ('cancelled', 'Ακυρώθηκε')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='internalorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.internalorder')),
            ],
            options={
                'verbose_name': 'Ιστορικό Κατάστασης',
                'verbose_name_plural': 'Ιστορικά Κατάστασης',
                'ordering': ['-created_at'],
            },
        ),
    ]
