# Generated by Django 5.2.5 on 2026-03-31 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usercompany'),
        ('orders', '0003_remove_internalorder_branch_and_more'),
        ('products', '0004_alter_branch_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='internalorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='internalorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.company'),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='destination_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_to_branch', to='products.branch'),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_from_branch', to='products.branch'),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Υποβλήθηκε'), ('in_progress', 'Σε προετοιμασία'), ('ready_for_pickup', 'Έτοιμη για παραλαβή'), ('picked_up', 'Καθ’ οδόν'), ('delivered', 'Παραδόθηκε'), ('cancelled', 'Ακυρώθηκε')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='internalorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='internalorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='old_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
