# Generated by Django 5.2.5 on 2026-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_internalorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalorderitem',
            name='picked_up_by_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalorderitem',
            name='pickup_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalorderitem',
            name='pickup_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='internalorder',
            name='status',
            field=models.CharField(choices=[('submitted', 'Υποβλήθηκε'), ('in_progress', 'Σε προετοιμασία'), ('ready_for_pickup', 'Έτοιμη για παραλαβή'), ('picked_up', 'Παραλήφθηκε / Σε διαδρομή'), ('delivered', 'Παραδόθηκε / Κλειστή'), ('cancelled', 'Ακυρώθηκε')], default='submitted', max_length=30),
        ),
    ]
